import type {NextPage} from 'next'
import Head from 'next/head'
import {Sidebar} from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar/>
        {/*  Feeds */}
        {/*  Widgets */}

        {/*  Modal */}
      </main>

    </div>
  )
}

export default Home
