import type {NextPage} from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        {/*  Sidebar */}
        {/*  Feeds */}
        {/*  Widgets */}

        {/*  Modal */}
      </main>

    </div>
  )
}

export default Home
